[package]
name = "ngrok_get_tunnel_url"
version = "1.0.0"
edition = "2024"

[dependencies]
reqwest = { version="0.12.15", features=["rustls-tls", "json"], default-features=false }
thiserror = "2.0"
serde = "1.0"
serde_derive = "1.0"
